server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/sanmonros/micro-tutorial/microservice-curso
          search-paths: config-data
  application:
    name: config-server
